# remote_theme: pages-themes/minimal@v0.2.0
# plugins: - jekyll-remote-theme

### VALUES YOU SHOULD CHANGE ###
permalink: /index.html
# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Lemoon's Blog
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website powered by Jekyll
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: Lemoon Can
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Welcome
# email: Your E-Mail address for the email button.
email: email@example.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: LemoonCan
codepen_username: exampleUser
dev_username: exampleUser
linkedin_username: exampleUser
twitter_username: exampleUser


# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: ""

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
